CREATE TABLE USUARIO
(
N_USUARIO VARCHAR2(20) NOT NULL
, N_NOMBREUSU VARCHAR2(50) NOT NULL
, N_APELLIDOUSU VARCHAR2(50) NOT NULL
, N_CONTRASENA VARCHAR2(20) NOT NULL 
, CONSTRAINT USUARIO_PK PRIMARY KEY
(
 N_USUARIO
)
ENABLE
)
;

CREATE TABLE CUENTA
(
K_NUMCUENTA NUMBER(10,0) NOT NULL
, Q_SALDO NUMBER(20,0) NOT NULL
, CONSTRAINT CUENTA_PK PRIMARY KEY
(
 K_NUMCUENTA
)
ENABLE
)
;

CREATE TABLE DOCENTE
(
K_IDDOCENTE NUMBER(12,0) NOT NULL
, N_NOMBREDOC VARCHAR2(20) NOT NULL
, N_APELLIDO VARCHAR2(20) NOT NULL
, N_CORREO VARCHAR2(20) NOT NULL
, CONSTRAINT DOCENTE_PK PRIMARY KEY 
(
K_IDDOCENTE
)
ENABLE
)
;

CREATE TABLE CURSOS
(
K_CODCURSO NUMBER(10,0) NOT NULL
, N_NOMCURSO VARCHAR2(20) NOT NULL
, N_DESCRIPCION VARCHAR2(200) NOT NULL
, N_DIRIMAGEN VARCHAR2(50) NOT NULL
, CONSTRAINT CURSOS_PK PRIMARY KEY
(
 K_CODCURSO
)
ENABLE
)
;

CREATE TABLE OFERTAS
(
 --POR DEFINIR
(
 --POR DEFINIR
)
ENABLE
)
;

-- FALTAN GENERAR LAS DE ROMPIMIENTO Y FORANEAS