CREATE TABLE USUARIO
(
N_USUARIO VARCHAR2(20) NOT NULL
, N_NOMBREUSU VARCHAR2(50) NOT NULL
, N_APELLIDOUSU VARCHAR2(50) NOT NULL
, N_CONTRASENA VARCHAR2(20) NOT NULL
, N_CORREO VARCHAR2(20)  
, CONSTRAINT USUARIO_PK PRIMARY KEY
(
 N_USUARIO
)
ENABLE
)
;

CREATE TABLE CUENTA
(
K_NUMCUENTA NUMBER(10,0) NOT NULL
, Q_SALDO NUMBER(20,0) NOT NULL
, CONSTRAINT CUENTA_PK PRIMARY KEY
(
 K_NUMCUENTA
)
ENABLE
)
;

CREATE TABLE CURSO
(
K_CODCURSO NUMBER(10,0) NOT NULL
, N_NOMCURSO VARCHAR2(20) NOT NULL
, N_DESCRIPCION VARCHAR2(200) NOT NULL
, N_DIRIMAGEN VARCHAR2(50) NOT NULL
, N_OFERTA NUMBER(3,0) NOT NULL
, N_PRECIO NUMBER(7,0) NOT NULL
, N_ESTADO NUMBER (1,0) NOT NULL
, CONSTRAINT CURSO_PK PRIMARY KEY
(
 K_CODCURSO
)
ENABLE
)
;

CREATE TABLE USUARIO_CURSO
(
K_USUARIO_CURSO NUMBER(10,0) NOT NULL
, N_USUARIO VARCHAR2(20) NOT NULL
, K_CODCURSO NUMBER(10,0) NOT NULL
, CONSTRAINT USUARIO_CURSO_PK PRIMARY KEY
(
 K_USUARIO_CURSO
)
ENABLE
)
;

ALTER TABLE USUARIO_CURSO
ADD CONSTRAINT USUARIO_CURSO_CURSO_FK FOREIGN KEY
(
 K_CODCURSO
)
REFERENCES CURSO
(
 K_CODCURSO
)
ENABLE
;
ALTER TABLE USUARIO_CURSO
ADD CONSTRAINT USUARIO_CURSO_USUARIO_FK FOREIGN KEY
(
 N_USUARIO
)
REFERENCES USUARIO
(
 N_USUARIO
)
ENABLE
;